table Sales
	lineageTag: 11615dd4-3e8e-4826-be00-bd0a118431e4

	measure AOV = DIVIDE(SUM(Sales[SalesAmount]), COUNT(Sales[OrderID]))
		lineageTag: 0991f428-fda9-4c89-b657-8354c22cc825

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column OrderID
		dataType: int64
		formatString: 0
		lineageTag: ff96796d-6459-4c5f-ba52-cf97aad91872
		summarizeBy: count
		sourceColumn: OrderID

		annotation SummarizationSetBy = Automatic

	column DateKey
		dataType: dateTime
		formatString: Long Date
		lineageTag: b22a4884-4ef3-4bca-b540-575f5028bc66
		summarizeBy: none
		sourceColumn: DateKey

		variation Variation
			isDefault
			relationship: ee265dfb-f056-4768-bd39-5dacdf053759
			defaultHierarchy: LocalDateTable_ac2ab37f-d024-4b86-adb9-17ed002189a1.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column CustomerID
		dataType: int64
		formatString: 0
		lineageTag: 4ee848f5-9d46-4a33-9f74-c902b7578557
		summarizeBy: none
		sourceColumn: CustomerID

		annotation SummarizationSetBy = Automatic

	column ProductID
		dataType: int64
		formatString: 0
		lineageTag: d4fb2515-1df1-4b76-b72b-8643005ddb1d
		summarizeBy: none
		sourceColumn: ProductID

		annotation SummarizationSetBy = Automatic

	column RegionID
		dataType: int64
		formatString: 0
		lineageTag: bae3b6d8-7c63-4b0f-8cba-bdf30dfc7f75
		summarizeBy: none
		sourceColumn: RegionID

		annotation SummarizationSetBy = Automatic

	column SalesRepID
		dataType: int64
		formatString: 0
		lineageTag: f363cc74-b881-499d-a2e7-3933c0f5d3fe
		summarizeBy: none
		sourceColumn: SalesRepID

		annotation SummarizationSetBy = Automatic

	column Quantity
		dataType: int64
		formatString: 0
		lineageTag: 5c56dd60-18f5-40ba-a6cc-323147566464
		summarizeBy: sum
		sourceColumn: Quantity

		annotation SummarizationSetBy = Automatic

	column SalesAmount
		dataType: int64
		formatString: 0
		lineageTag: d3414bdf-8d57-41f0-a3b2-8aea3b2eab49
		summarizeBy: sum
		sourceColumn: SalesAmount

		annotation SummarizationSetBy = Automatic

	partition Sales = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\TumpudiKarthikeya\Downloads\OrderDetails_Data\OrderDetails_Data\Sales.csv"),[Delimiter=",", Columns=8, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"OrderID", Int64.Type}, {"DateKey", type date}, {"CustomerID", Int64.Type}, {"ProductID", Int64.Type}, {"RegionID", Int64.Type}, {"SalesRepID", Int64.Type}, {"Quantity", Int64.Type}, {"SalesAmount", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

